# Generated by Django 5.2 on 2025-04-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydashboardlink',
            old_name='icon',
            new_name='icons',
        ),
    ]
