# Generated by Django 5.2 on 2025-04-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuploads',
            name='aadhar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='appointment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='dl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='esic_card',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='pan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='promotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
