# Generated by Django 5.2 on 2025-06-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
