# Generated by Django 5.2 on 2025-04-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
