# Generated by Django 5.2 on 2025-04-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_documentuploads_aadhar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_leaving',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dl',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='epf_member',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esic_card',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='probation_end',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reporting_to',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='uan',
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_doc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('m', 'M'), ('f', 'F'), ('Other', 'Other')], max_length=10),
        ),
    ]
