# Generated by Django 5.2 on 2025-06-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leaverequest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
