# Generated by Django 5.2 on 2025-04-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeedashboardlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedashboardlink',
            name='employee',
        ),
    ]
