# Generated by Django 5.2 on 2025-04-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_company_password_company_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='title',
            new_name='role_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='company',
        ),
    ]
