# Generated by Django 5.2 on 2025-05-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hrdashboardlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedashboardlink',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hrdashboardlink',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
