# Generated by Django 5.2 on 2025-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employeedashboardlink_active_hrdashboardlink_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydashboardlink',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
