# Generated by Django 5.2 on 2025-04-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='bank_doc',
            new_name='bank_details_pdf',
        ),
        migrations.RenameField(
            model_name='bankdetails',
            old_name='ifsc',
            new_name='ifsc_code',
        ),
    ]
