# Generated by Django 5.2 on 2025-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_attachment',
            field=models.FileField(blank=True, null=True, upload_to='bugs-attachement/'),
        ),
    ]
