# Generated by Django 5.2 on 2025-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_bank_doc_bankdetails_bank_details_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_details_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bank_pdfs/'),
        ),
    ]
