# Generated by Django 5.2 on 2025-06-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_attendance_user_remove_attendancesession_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_logs',
            field=models.JSONField(default=list),
        ),
    ]
