# Generated by Django 5.2 on 2025-06-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bug_bug_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='resolution_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
