# Generated by Django 5.2 on 2025-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bankdetails_bank_details_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuploads',
            name='aadhar',
            field=models.FileField(blank=True, null=True, upload_to='emp_adhar/'),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='appointment',
            field=models.FileField(blank=True, null=True, upload_to='emp_appointment/'),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='dl',
            field=models.FileField(blank=True, null=True, upload_to='emp_dl/'),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='esic_card',
            field=models.FileField(blank=True, null=True, upload_to='emp_esic_card/'),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='pan',
            field=models.FileField(blank=True, null=True, upload_to='emp_pan/'),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='emp_pic/'),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='promotion',
            field=models.FileField(blank=True, null=True, upload_to='emp_promotion/'),
        ),
        migrations.AlterField(
            model_name='documentuploads',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='emp_resume/'),
        ),
    ]
