# Generated by Django 5.2 on 2025-05-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_holiday_created_at_alter_holiday_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='day_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
