# Generated by Django 5.2 on 2025-04-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_documentuploads_aadhar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentUploads',
            new_name='EmployeeDocument',
        ),
    ]
