# Generated by Django 5.2 on 2025-04-18 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_documentuploads_employeedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='aadhar',
            field=models.FileField(blank=True, null=True, upload_to='adhar_documents/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='appointment',
            field=models.FileField(blank=True, null=True, upload_to='appointmen_documents/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='dl',
            field=models.FileField(blank=True, null=True, upload_to='dl_documents/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='epf_member',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='esic_card',
            field=models.FileField(blank=True, null=True, upload_to='esic_documents/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='insurance_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='pan',
            field=models.FileField(blank=True, null=True, upload_to='pan_documents/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='emp_documents/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='promotion',
            field=models.FileField(blank=True, null=True, upload_to='promotion_documents/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume_documents/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='uan',
            field=models.CharField(max_length=50),
        ),
    ]
