# Generated by Django 5.2 on 2025-05-12 10:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attendance_active_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_image_path),
        ),
    ]
