# Generated by Django 5.2 on 2025-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_employeedocument_aadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officedetails',
            name='job_role',
            field=models.CharField(default='Employee', max_length=100),
            preserve_default=False,
        ),
    ]
