# Generated by Django 5.2 on 2025-04-18 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_officedetails_job_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='to_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='admin_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('PL', 'Personal Leave')], default='CL', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('HR Approved', 'HR Approved'), ('HR Rejected', 'HR Rejected'), ('Admin Approved', 'Admin Approved'), ('Admin Rejected', 'Admin Rejected')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave', models.FloatField(default=0.0)),
                ('personal_leave', models.FloatField(default=0.0)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
