# Generated by Django 5.2 on 2025-05-15 04:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.company_logo),
        ),
    ]
