# Generated by Django 5.2 on 2025-05-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_company_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
