# Generated by Django 5.2 on 2025-04-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_leaverequest_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='start_date',
            new_name='from_date',
        ),
    ]
