# Generated by Django 5.2 on 2025-06-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attendance_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='company',
        ),
    ]
