# Generated by Django 5.2 on 2025-04-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_start_date_leaverequest_from_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='end_date',
            new_name='to_data',
        ),
    ]
