# Generated by Django 5.2 on 2025-06-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_role_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officedetails',
            name='date_of_leaving',
        ),
        migrations.RemoveField(
            model_name='officedetails',
            name='job_role',
        ),
    ]
