# Generated by Django 5.2 on 2025-04-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_end_date_leaverequest_to_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='to_data',
            new_name='to_date',
        ),
    ]
