# Generated by Django 5.2 on 2025-05-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='bug',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to='core.employee'),
        ),
    ]
