# Generated by Django 5.2 on 2025-06-09 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_officedetails_date_of_leaving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_document',
            field=models.FileField(blank=True, help_text='Optional. Upload supporting document (PDF, JPG, PNG, JPEG).', null=True, upload_to='leave_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
