# Generated by Django 5.2 on 2025-06-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_leaverequest_leave_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('PL', 'Personal Leave'), ('SL', 'Sick Leave')], max_length=2),
        ),
    ]
