# Generated by Django 5.2 on 2025-05-21 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_bug_assigned_to_bug_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='discription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
