# Generated by Django 5.2 on 2025-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_bug_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='bug',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_bugs', to='core.employee'),
        ),
    ]
