# Generated by Django 5.2 on 2025-05-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_bug_assigned_to_bug_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='discription',
            new_name='description',
        ),
    ]
