# Generated by Django 5.2 on 2025-06-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_date_holiday_start_date_holiday_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='end_date',
        ),
    ]
