# Generated by Django 5.2 on 2025-05-22 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_task_active_task_created_by_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(related_name='tasks', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_tasks', to='core.employee'),
        ),
    ]
