# Generated by Django 5.2 on 2025-05-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_task_members_alter_task_team_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
    ]
